spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:h2:mem:drones
drone:
  min-battery-capacity-for-loading: 25

---

spring:
  config:
    activate:
      on-profile: dev
  h2:
    console:
      enabled: true
server:
  error:
    include-message: always