spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:h2:mem:drones
drone:
  battery:
    min-capacity-for-loading: 25
    log.rate: 600000

---

spring:
  config:
    activate:
      on-profile: dev
  h2:
    console:
      enabled: true
server:
  error:
    include-message: always

---

spring:
  config:
    activate:
      on-profile: kafka
  kafka:
    bootstrap-servers:
      - kafka1:19092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: 0